<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>

    <TargetFramework>net9.0-windows</TargetFramework>

    <UseWindowsForms>true</UseWindowsForms>

    <RootNamespace></RootNamespace>

    <StartupObject>VBImGuiDx9.Sample.Program</StartupObject>

    <OptionStrict>On</OptionStrict>
    <OptionExplicit>On</OptionExplicit>
    <OptionInfer>On</OptionInfer>

    <ImplicitUsings>disable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\VBImGuiDx9.vbproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="My Project\**" />
    <EmbeddedResource Remove="My Project\**" />
    <None Remove="My Project\**" />
  </ItemGroup>

</Project>
