Option Strict On
Option Explicit On
Option Infer On

Imports System
Imports ImGuiNET

Namespace VBImGuiDx9.Core

    ''' <summary>
    ''' Controls the Dear ImGui frame lifecycle.
    '''
    ''' Lifecycle:
    '''
    '''     BeginFrame()
    '''         ↓
    '''     ImGui.NewFrame()
    '''         ↓
    '''     UI code
    '''         ↓
    '''     EndFrame()
    '''         ↓
    '''     ImGui.Render()
    '''         ↓
    '''     DrawData
    '''
    ''' A new frame may be started after the previous frame
    ''' has been rendered.
    ''' </summary>
    Public NotInheritable Class ImGuiFrameController

#Region "Fields"

        Private ReadOnly _contextManager As ImGuiContextManager

        Private _frameActive As Boolean
        Private _rendered As Boolean
        Private _disposed As Boolean

#End Region

#Region "Constructor"

        ''' <summary>
        ''' Creates an ImGui frame controller.
        ''' </summary>
        Public Sub New(
            contextManager As ImGuiContextManager)

            If contextManager Is Nothing Then
                Throw New ArgumentNullException(
                    NameOf(contextManager))
            End If

            If Not contextManager.IsInitialized Then
                Throw New InvalidOperationException(
                    "ImGui context must be initialized before creating the frame controller.")
            End If

            _contextManager = contextManager

        End Sub

#End Region

#Region "Properties"

        ''' <summary>
        ''' Gets whether an ImGui frame is currently active.
        ''' </summary>
        Public ReadOnly Property IsFrameActive As Boolean

            Get
                Return _frameActive
            End Get

        End Property

        ''' <summary>
        ''' Gets whether the current frame has been rendered.
        ''' </summary>
        Public ReadOnly Property IsRendered As Boolean

            Get
                Return _rendered
            End Get

        End Property

        ''' <summary>
        ''' Gets the ImGui IO interface.
        ''' </summary>
        Public ReadOnly Property IO As ImGuiIOPtr

            Get

                ThrowIfDisposed()

                Return _contextManager.IO

            End Get

        End Property

#End Region

#Region "Frame"

        ''' <summary>
        ''' Begins a new Dear ImGui frame.
        '''
        ''' A previous frame may already have been rendered.
        ''' That is the normal frame-to-frame lifecycle.
        ''' </summary>
        Public Sub BeginFrame()

            ThrowIfDisposed()

            If _frameActive Then

                Throw New InvalidOperationException(
                    "An ImGui frame is already active.")

            End If

            ' The previous frame is complete.
            ' Starting a new frame resets the rendered state.
            _rendered = False

            ImGui.SetCurrentContext(
                _contextManager.Context)

            ImGui.NewFrame()

            _frameActive = True

        End Sub

        ''' <summary>
        ''' Ends the current Dear ImGui frame and generates ImDrawData.
        ''' </summary>
        Public Sub EndFrame()

            ThrowIfDisposed()

            If Not _frameActive Then

                Throw New InvalidOperationException(
                    "There is no active ImGui frame.")

            End If

            ImGui.Render()

            _frameActive = False
            _rendered = True

        End Sub

#End Region

#Region "Draw Data"

        ''' <summary>
        ''' Gets the draw data generated by the current frame.
        ''' </summary>
        Public ReadOnly Property DrawData As ImDrawDataPtr

            Get

                ThrowIfDisposed()

                If Not _rendered Then

                    Throw New InvalidOperationException(
                        "ImGui.Render() must be called before accessing draw data.")

                End If

                Return ImGui.GetDrawData()

            End Get

        End Property

#End Region

#Region "Private"

        ''' <summary>
        ''' Throws when the frame controller has already been disposed.
        ''' </summary>
        Private Sub ThrowIfDisposed()

            If _disposed Then

                Throw New ObjectDisposedException(
                    NameOf(ImGuiFrameController))

            End If

        End Sub

#End Region

#Region "Dispose"

        ''' <summary>
        ''' Releases the frame controller.
        ''' </summary>
        Public Sub Dispose()

            If _disposed Then
                Return
            End If

            _frameActive = False
            _rendered = False
            _disposed = True

        End Sub

#End Region

    End Class

End Namespace